# Generated by Django 3.2 on 2021-05-28 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_for',
            field=models.TextField(default=datetime.time(17, 30)),
        ),
    ]
