# Generated by Django 3.2 on 2021-05-28 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_order_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_for',
        ),
    ]
