# Generated by Django 3.2 on 2021-05-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='cat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='cyo',
            field=models.BooleanField(default=False),
        ),
    ]
