# Generated by Django 3.2 on 2021-05-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210506_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vegetarian',
            field=models.BooleanField(default=False),
        ),
    ]
