# Generated by Django 3.2 on 2021-05-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_vegetarian'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='vegetarian',
            field=models.BooleanField(),
        ),
    ]
