# Generated by Django 3.2 on 2021-05-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210507_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='custom_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
