# Generated by Django 3.2 on 2021-05-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_custom_burger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_burger',
            name='price',
        ),
        migrations.AddField(
            model_name='custom_burger',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='custom_burger',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
