# Generated by Django 3.2 on 2021-05-28 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210526_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='custom_name',
        ),
    ]
