# Generated by Django 3.2 on 2021-05-28 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_product_custom_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_burger',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='custom_burger',
            name='likes',
        ),
    ]
