# Generated by Django 3.2 on 2021-06-08 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20210608_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_burger',
            name='ingredients',
        ),
    ]
