# Generated by Django 3.2 on 2021-06-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_custom_burger_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_burger',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='ingredient', to='products.Ingredients'),
        ),
    ]
