# Generated by Django 3.2 on 2021-06-08 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_custom_burger_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_burger',
            name='buns',
        ),
        migrations.RemoveField(
            model_name='custom_burger',
            name='burger',
        ),
        migrations.RemoveField(
            model_name='custom_burger',
            name='category',
        ),
        migrations.RemoveField(
            model_name='custom_burger',
            name='cheese',
        ),
        migrations.RemoveField(
            model_name='custom_burger',
            name='extras',
        ),
        migrations.RemoveField(
            model_name='custom_burger',
            name='salads',
        ),
        migrations.RemoveField(
            model_name='custom_burger',
            name='sauce',
        ),
    ]
