# Generated by Django 3.2 on 2021-06-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20210608_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_burger',
            name='buns',
        ),
        migrations.RemoveField(
            model_name='custom_burger',
            name='burger',
        ),
        migrations.RemoveField(
            model_name='custom_burger',
            name='category',
        ),
        migrations.RemoveField(
            model_name='custom_burger',
            name='cheese',
        ),
        migrations.RemoveField(
            model_name='custom_burger',
            name='extras',
        ),
        migrations.RemoveField(
            model_name='custom_burger',
            name='salads',
        ),
        migrations.RemoveField(
            model_name='custom_burger',
            name='sauce',
        ),
        migrations.AddField(
            model_name='custom_burger',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='ingredient', to='products.Ingredients'),
        ),
    ]
