# Generated by Django 3.2 on 2021-06-09 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20210608_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_burger',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='cyo',
        ),
        migrations.AddField(
            model_name='custom_burger',
            name='buns',
            field=models.ManyToManyField(blank=True, related_name='buns', to='products.Ingredients'),
        ),
        migrations.AddField(
            model_name='custom_burger',
            name='burger',
            field=models.ManyToManyField(blank=True, related_name='burger', to='products.Ingredients'),
        ),
        migrations.AddField(
            model_name='custom_burger',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_burger', to='products.category'),
        ),
        migrations.AddField(
            model_name='custom_burger',
            name='cheese',
            field=models.ManyToManyField(blank=True, related_name='cheese', to='products.Ingredients'),
        ),
        migrations.AddField(
            model_name='custom_burger',
            name='extras',
            field=models.ManyToManyField(blank=True, related_name='extras', to='products.Ingredients'),
        ),
        migrations.AddField(
            model_name='custom_burger',
            name='salads',
            field=models.ManyToManyField(blank=True, related_name='salads', to='products.Ingredients'),
        ),
        migrations.AddField(
            model_name='custom_burger',
            name='sauce',
            field=models.ManyToManyField(blank=True, related_name='sauce', to='products.Ingredients'),
        ),
    ]
