# Generated by Django 3.2 on 2021-06-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20210609_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_burger',
            name='burger',
        ),
        migrations.RemoveField(
            model_name='custom_burger',
            name='cheese',
        ),
        migrations.RemoveField(
            model_name='custom_burger',
            name='extras',
        ),
        migrations.RemoveField(
            model_name='custom_burger',
            name='salads',
        ),
        migrations.RemoveField(
            model_name='custom_burger',
            name='sauce',
        ),
        migrations.AddField(
            model_name='custom_burger',
            name='burgers',
            field=models.ManyToManyField(blank=True, related_name='burgers', to='products.Ingredients'),
        ),
        migrations.AddField(
            model_name='custom_burger',
            name='cheeses',
            field=models.ManyToManyField(blank=True, related_name='cheeses', to='products.Ingredients'),
        ),
        migrations.AddField(
            model_name='custom_burger',
            name='extra',
            field=models.ManyToManyField(blank=True, related_name='extra', to='products.Ingredients'),
        ),
        migrations.AddField(
            model_name='custom_burger',
            name='salad',
            field=models.ManyToManyField(blank=True, related_name='salad', to='products.Ingredients'),
        ),
        migrations.AddField(
            model_name='custom_burger',
            name='sauces',
            field=models.ManyToManyField(blank=True, related_name='sauces', to='products.Ingredients'),
        ),
    ]
