# Generated by Django 3.2 on 2021-06-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20210609_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_burger',
            name='buns',
        ),
        migrations.AddField(
            model_name='custom_burger',
            name='buns',
            field=models.ManyToManyField(blank=True, related_name='buns', to='products.Ingredients'),
        ),
        migrations.RemoveField(
            model_name='custom_burger',
            name='burger',
        ),
        migrations.AddField(
            model_name='custom_burger',
            name='burger',
            field=models.ManyToManyField(blank=True, related_name='burger', to='products.Ingredients'),
        ),
        migrations.RemoveField(
            model_name='custom_burger',
            name='cheese',
        ),
        migrations.AddField(
            model_name='custom_burger',
            name='cheese',
            field=models.ManyToManyField(blank=True, related_name='cheese', to='products.Ingredients'),
        ),
        migrations.RemoveField(
            model_name='custom_burger',
            name='extras',
        ),
        migrations.AddField(
            model_name='custom_burger',
            name='extras',
            field=models.ManyToManyField(blank=True, related_name='extras', to='products.Ingredients'),
        ),
        migrations.RemoveField(
            model_name='custom_burger',
            name='salads',
        ),
        migrations.AddField(
            model_name='custom_burger',
            name='salads',
            field=models.ManyToManyField(blank=True, related_name='salads', to='products.Ingredients'),
        ),
        migrations.RemoveField(
            model_name='custom_burger',
            name='sauce',
        ),
        migrations.AddField(
            model_name='custom_burger',
            name='sauce',
            field=models.ManyToManyField(blank=True, related_name='sauce', to='products.Ingredients'),
        ),
    ]
